const countries = {
  get(alias, name) {
    if (alias) {
      let country = this.table.find(x => x.alias.toLowerCase() === alias.toLowerCase());
      if (country) return country;
    }

    if (name) {
      country = this.table.find(x => x.name.toLowerCase() === name.toLowerCase());
      if (country) return country;
    }

    return false;
  },

  random() {
    return this.table[Math.floor(Math.random() * this.table.length)];
  },

  table: [
          { name: "Afghanistan", flag: "🇦🇫", alias: "AFG" },
          { name: "Albania", flag: "🇦🇱", alias: "ALB" },
          { name: "Algeria", flag: "🇩🇿", alias: "DZA" },
          { name: "Andorra", flag: "🇦🇩", alias: "AND" },
          { name: "Angola", flag: "🇦🇴", alias: "AGO" },
          { name: "Antigua and Barbuda", flag: "🇦🇬", alias: "ATG" },
          { name: "Argentina", flag: "🇦🇷", alias: "ARG" },
          { name: "Armenia", flag: "🇦🇲", alias: "ARM" },
          { name: "Australia", flag: "🇦🇺", alias: "AUS" },
          { name: "Austria", flag: "🇦🇹", alias: "AUT" },
          { name: "Azerbaijan", flag: "🇦🇿", alias: "AZE" },
          { name: "Bahamas", flag: "🇧🇸", alias: "BHS" },
          { name: "Bahrain", flag: "🇧🇭", alias: "BHR" },
          { name: "Bangladesh", flag: "🇧🇩", alias: "BGD" },
          { name: "Barbados", flag: "🇧🇧", alias: "BRB" },
          { name: "Belarus", flag: "🇧🇾", alias: "BLR" },
          { name: "Belgium", flag: "🇧🇪", alias: "BEL" },
          { name: "Belize", flag: "🇧🇿", alias: "BLZ" },
          { name: "Benin", flag: "🇧🇯", alias: "BEN" },
          { name: "Bhutan", flag: "🇧🇹", alias: "BTN" },
          { name: "Bolivia", flag: "🇧🇴", alias: "BOL" },
          { name: "Bosnia and Herzegovina", flag: "🇧🇦", alias: "BIH" },
          { name: "Botswana", flag: "🇧🇼", alias: "BWA" },
          { name: "Brazil", flag: "🇧🇷", alias: "BRA" },
          { name: "Brunei", flag: "🇧🇳", alias: "BRN" },
          { name: "Bulgaria", flag: "🇧🇬", alias: "BGR" },
          { name: "Burkina Faso", flag: "🇧🇫", alias: "BFA" },
          { name: "Burundi", flag: "🇧🇮", alias: "BDI" },
          { name: "Cabo Verde", flag: "🇨🇻", alias: "CPV" },
          { name: "Cambodia", flag: "🇰🇭", alias: "KHM" },
          { name: "Cameroon", flag: "🇨🇲", alias: "CMR" },
          { name: "Canada", flag: "🇨🇦", alias: "CAN" },
          { name: "Central African Republic", flag: "🇨🇫", alias: "CAF" },
          { name: "Chad", flag: "🇹🇩", alias: "TCD" },
          { name: "Chile", flag: "🇨🇱", alias: "CHL" },
          { name: "China", flag: "🇨🇳", alias: "CHN" },
          { name: "Colombia", flag: "🇨🇴", alias: "COL" },
          { name: "Comoros", flag: "🇰🇲", alias: "COM" },
          { name: "Republic of the Congo", flag: "🇨🇬", alias: "ROC" },
          { name: "Democratic Republic of the Congo", flag: "🇨🇩", alias: "DRC" },
          { name: "Costa Rica", flag: "🇨🇷", alias: "CRI" },
          { name: "Croatia", flag: "🇭🇷", alias: "HRV" },
          { name: "Cuba", flag: "🇨🇺", alias: "CUB" },
          { name: "Cyprus", flag: "🇨🇾", alias: "CYP" },
          { name: "Czech Republic", flag: "🇨🇿", alias: "CZE" },
          { name: "Denmark", flag: "🇩🇰", alias: "DNK" },
          { name: "Djibouti", flag: "🇩🇯", alias: "DJI" },
          { name: "Dominica", flag: "🇩🇲", alias: "DMA" },
          { name: "Dominican Republic", flag: "🇩🇴", alias: "DOM" },
          { name: "Ecuador", flag: "🇪🇨", alias: "ECU" },
          { name: "Egypt", flag: "🇪🇬", alias: "EGY" },
          { name: "El Salvador", flag: "🇸🇻", alias: "SLV" },
          { name: "Equatorial Guinea", flag: "🇬🇶", alias: "GNQ" },
          { name: "Eritrea", flag: "🇪🇷", alias: "ERI" },
          { name: "Estonia", flag: "🇪🇪", alias: "EST" },
          { name: "Eswatini", flag: "🇸🇿", alias: "SWZ" },
          { name: "Ethiopia", flag: "🇪🇹", alias: "ETH" },
          { name: "Fiji", flag: "🇫🇯", alias: "FJI" },
          { name: "Finland", flag: "🇫🇮", alias: "FIN" },
          { name: "France", flag: "🇫🇷", alias: "FRA" },
          { name: "Gabon", flag: "🇬🇦", alias: "GAB" },
          { name: "Gambia", flag: "🇬🇲", alias: "GMB" },
          { name: "Georgia", flag: "🇬🇪", alias: "GEO" },
          { name: "Germany", flag: "🇩🇪", alias: "DEU" },
          { name: "Ghana", flag: "🇬🇭", alias: "GHA" },
          { name: "Greece", flag: "🇬🇷", alias: "GRC" },
          { name: "Grenada", flag: "🇬🇩", alias: "GRD" },
          { name: "Guatemala", flag: "🇬🇹", alias: "GTM" },
          { name: "Guinea", flag: "🇬🇳", alias: "GIN" },
          { name: "Guinea-Bissau", flag: "🇬🇼", alias: "GNB" },
          { name: "Guyana", flag: "🇬🇾", alias: "GUY" },
          { name: "Haiti", flag: "🇭🇹", alias: "HTI" },
          { name: "Honduras", flag: "🇭🇳", alias: "HND" },
          { name: "Hungary", flag: "🇭🇺", alias: "HUN" },
          { name: "Iceland", flag: "🇮🇸", alias: "ISL" },
          { name: "India", flag: "🇮🇳", alias: "IND" },
          { name: "Indonesia", flag: "🇮🇩", alias: "IDN" },
          { name: "Iran", flag: "🇮🇷", alias: "IRN" },
          { name: "Iraq", flag: "🇮🇶", alias: "IRQ" },
          { name: "Ireland", flag: "🇮🇪", alias: "IRL" },
          { name: "Israel", flag: "🇮🇱", alias: "ISR" },
          { name: "Italy", flag: "🇮🇹", alias: "ITA" },
          { name: "Jamaica", flag: "🇯🇲", alias: "JAM" },
          { name: "Japan", flag: "🇯🇵", alias: "JPN" },
          { name: "Jordan", flag: "🇯🇴", alias: "JOR" },
          { name: "Kazakhstan", flag: "🇰🇿", alias: "KAZ" },
          { name: "Kenya", flag: "🇰🇪", alias: "KEN" },
          { name: "Kiribati", flag: "🇰🇮", alias: "KIR" },
          { name: "Kosovo", flag: "🇽🇰", alias: "XKX" },
          { name: "Kuwait", flag: "🇰🇼", alias: "KWT" },
          { name: "Kyrgyzstan", flag: "🇰🇬", alias: "KGZ" },
          { name: "Laos", flag: "🇱🇦", alias: "LAO" },
          { name: "Latvia", flag: "🇱🇻", alias: "LVA" },
          { name: "Lebanon", flag: "🇱🇧", alias: "LBN" },
          { name: "Lesotho", flag: "🇱🇸", alias: "LSO" },
          { name: "Liberia", flag: "🇱🇷", alias: "LBR" },
          { name: "Libya", flag: "🇱🇾", alias: "LBY" },
          { name: "Liechtenstein", flag: "🇱🇮", alias: "LIE" },
          { name: "Lithuania", flag: "🇱🇹", alias: "LTU" },
          { name: "Luxembourg", flag: "🇱🇺", alias: "LUX" },
          { name: "Madagascar", flag: "🇲🇬", alias: "MDG" },
          { name: "Malawi", flag: "🇲🇼", alias: "MWI" },
          { name: "Malaysia", flag: "🇲🇾", alias: "MYS" },
          { name: "Maldives", flag: "🇲🇻", alias: "MDV" },
          { name: "Mali", flag: "🇲🇱", alias: "MLI" },
          { name: "Malta", flag: "🇲🇹", alias: "MLT" },
          { name: "Marshall Islands", flag: "🇲🇭", alias: "MHL" },
          { name: "Mauritania", flag: "🇲🇷", alias: "MRT" },
          { name: "Mauritius", flag: "🇲🇺", alias: "MUS" },
          { name: "Mexico", flag: "🇲🇽", alias: "MEX" },
          { name: "Micronesia", flag: "🇫🇲", alias: "FSM" },
          { name: "Moldova", flag: "🇲🇩", alias: "MDA" },
          { name: "Monaco", flag: "🇲🇨", alias: "MCO" },
          { name: "Mongolia", flag: "🇲🇳", alias: "MNG" },
          { name: "Montenegro", flag: "🇲🇪", alias: "MNE" },
          { name: "Morocco", flag: "🇲🇦", alias: "MAR" },
          { name: "Mozambique", flag: "🇲🇿", alias: "MOZ" },
          { name: "Myanmar", flag: "🇲🇲", alias: "MMR" },
          { name: "Namibia", flag: "🇳🇦", alias: "NAM" },
          { name: "Naoero", flag: "🇳🇷", alias: "NRU" },
          { name: "Nepal", flag: "🇳🇵", alias: "NPL" },
          { name: "Netherlands", flag: "🇳🇱", alias: "NLD" },
          { name: "New Zealand", flag: "🇳🇿", alias: "NZL" },
          { name: "Nicaragua", flag: "🇳🇮", alias: "NIC" },
          { name: "Niger", flag: "🇳🇪", alias: "NER" },
          { name: "Nigeria", flag: "🇳🇬", alias: "NGA" },
          { name: "North Korea", flag: "🇰🇵", alias: "PRK" },
          { name: "North Macedonia", flag: "🇲🇰", alias: "MKD" },
          { name: "Norway", flag: "🇳🇴", alias: "NOR" },
          { name: "Oman", flag: "🇴🇲", alias: "OMN" },
          { name: "Pakistan", flag: "🇵🇰", alias: "PAK" },
          { name: "Palau", flag: "🇵🇼", alias: "PLW" },
          { name: "Panama", flag: "🇵🇦", alias: "PAN" },
          { name: "Papua New Guinea", flag: "🇵🇬", alias: "PNG" },
          { name: "Paraguay", flag: "🇵🇾", alias: "PRY" },
          { name: "Peru", flag: "🇵🇪", alias: "PER" },
          { name: "Philippines", flag: "🇵🇭", alias: "PHL" },
          { name: "Poland", flag: "🇵🇱", alias: "POL" },
          { name: "Portugal", flag: "🇵🇹", alias: "PRT" },
          { name: "Qatar", flag: "🇶🇦", alias: "QAT" },
          { name: "Romania", flag: "🇷🇴", alias: "ROU" },
          { name: "Russia", flag: "🇷🇺", alias: "RUS" },
          { name: "Rwanda", flag: "🇷🇼", alias: "RWA" },
          { name: "Saint Kitts and Nevis", flag: "🇰🇳", alias: "KNA" },
          { name: "Saint Lucia", flag: "🇱🇨", alias: "LCA" },
          { name: "Saint Vincent and the Grenadines", flag: "🇻🇨", alias: "VCT" },
          { name: "Samoa", flag: "🇼🇸", alias: "WSM" },
          { name: "San Marino", flag: "🇸🇲", alias: "SMR" },
          { name: "Sao Tome and Principe", flag: "🇸🇹", alias: "STP" },
          { name: "Saudi Arabia", flag: "🇸🇦", alias: "SAU" },
          { name: "Senegal", flag: "🇸🇳", alias: "SEN" },
          { name: "Serbia", flag: "🇷🇸", alias: "SRB" },
          { name: "Seychelles", flag: "🇸🇨", alias: "SYC" },
          { name: "Sierra Leone", flag: "🇸🇱", alias: "SLE" },
          { name: "Singapore", flag: "🇸🇬", alias: "SGP" },
          { name: "Slovakia", flag: "🇸🇰", alias: "SVK" },
          { name: "Slovenia", flag: "🇸🇮", alias: "SVN" },
          { name: "Solomon Islands", flag: "🇸🇧", alias: "SLB" },
          { name: "Somalia", flag: "🇸🇴", alias: "SOM" },
          { name: "South Africa", flag: "🇿🇦", alias: "ZAF" },
          { name: "South Korea", flag: "🇰🇷", alias: "KOR" },
          { name: "South Sudan", flag: "🇸🇸", alias: "SSD" },
          { name: "Spain", flag: "🇪🇸", alias: "ESP" },
          { name: "Sri Lanka", flag: "🇱🇰", alias: "LKA" },
          { name: "Sudan", flag: "🇸🇩", alias: "SDN" },
          { name: "Suriname", flag: "🇸🇷", alias: "SUR" },
          { name: "Sweden", flag: "🇸🇪", alias: "SWE" },
          { name: "Switzerland", flag: "🇨🇭", alias: "CHE" },
          { name: "Syria", flag: "🇸🇾", alias: "SYR" },
          { name: "Tajikistan", flag: "🇹🇯", alias: "TJK" },
          { name: "Tanzania", flag: "🇹🇿", alias: "TZA" },
          { name: "Thailand", flag: "🇹🇭", alias: "THA" },
          { name: "Timor-Leste", flag: "🇹🇱", alias: "TLS" },
          { name: "Togo", flag: "🇹🇬", alias: "TGO" },
          { name: "Tonga", flag: "🇹🇴", alias: "TON" },
          { name: "Trinidad and Tobago", flag: "🇹🇹", alias: "TTO" },
          { name: "Tunisia", flag: "🇹🇳", alias: "TUN" },
          { name: "Turkey", flag: "🇹🇷", alias: "TUR" },
          { name: "Turkmenistan", flag: "🇹🇲", alias: "TKM" },
          { name: "Tuvalu", flag: "🇹🇻", alias: "TUV" },
          { name: "Uganda", flag: "🇺🇬", alias: "UGA" },
          { name: "Ukraine", flag: "🇺🇦", alias: "UKR" },
          { name: "United Arab Emirates", flag: "🇦🇪", alias: "ARE" },
          { name: "United Kingdom", flag: "🇬🇧", alias: "GBR" },
          { name: "United States", flag: "🇺🇸", alias: "USA" },
          { name: "Uruguay", flag: "🇺🇾", alias: "URY" },
          { name: "Uzbekistan", flag: "🇺🇿", alias: "UZB" },
          { name: "Vanuatu", flag: "🇻🇺", alias: "VUT" },
          { name: "Vatican City", flag: "🇻🇦", alias: "VAT" },
          { name: "Venezuela", flag: "🇻🇪", alias: "VEN" },
          { name: "Vietnam", flag: "🇻🇳", alias: "VNM" },
          { name: "Yemen", flag: "🇾🇪", alias: "YEM" },
          { name: "Zambia", flag: "🇿🇲", alias: "ZMB" },
          { name: "Zimbabwe", flag: "🇿🇼", alias: "ZWE" },
  ],
}